CREATE DATABASE taskslist;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS tarefas (
    id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
    titulo VARCHAR NOT NULL,
    descricao VARCHAR,
    status VARCHAR NOT NULL,
    data TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
